### ISSUE TITLE
missing map bsp?

### ISSUE THREAD

**Issue by Motarashimasu** [ipkpjersi/SOCOMINS#1]
you have the files for everything except the rest of the bsp's for the remaining maps... the only maps with BSPs in your folders is Blizzard and crossroads.

**Comment by ipkpjersi** [comment]
Hi,

I believe the copy I have only ever had 3 maps, and the third map was over 100MB however GitHub has a 100MB file limit so it was not able to be included. I believe you'll have to find any other map files elsewhere.

Cheers.
